# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'assignment' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  # Pods for assignment
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  
  pod 'Socket.IO-Client-Swift', '~> 15.0.0'

end
